---
title: "Acidification assesmment"
author: Anna Lackner
date: today
format:
    html:
        embed-resources: true
        toc: true
        toc-depth: 3
        warning: true
        smooth-scroll: true
        code-fold: true
execute: 
  cache: true
---

Working with Stephan Köhler's excel model. 

```{r load packages, echo = FALSE}
library(tidyverse)
```


## VM

```{r}
data <- readRDS("../results/r_py/data_1.rds") %>% as_tibble()


```

```{r}
#| cache-refresh: true
#| label: calc-weigths
library(dplyr)
library(ggplot2)
library(matrixStats)
library(PSCBS)

# Calculate the weights for each station
weights <- data %>%
  group_by(mvm_id) %>%
  summarise(weight = 1 / n()) %>%
  ungroup()

# Merge weights with the original data
data_with_weights <- data %>%
  left_join(weights, by = "mvm_id")
```

```{r}
#| cache-refresh: true
#| label: tbl-chemistry
#| tbl-cap: Water chemistry values measured and modelled for the stations used in this study, weighted porportional to number of samples for each station. 
library(vtable)
library(matrixStats)

# add min and max of each station to the table
data_table <- data_with_weights %>% mutate(
    `SO4 (mmol/l)` = as.numeric(SO4_mol * 1000),
    `Alk Acid (mmol/l)` = as.numeric(Alk_Acid_mol * 1000),
    `Organic charge (meq/l)` = as.numeric(org_charge * 1000), 
    `Sum of Cations (mmol/l)` = as.numeric(Sum.of.cations * 1000)
    ) %>% select(-c(
        SO4_mol, charge_diff, Alk_Acid_mol, org_charge, Sum.of.cations, Sum.of.anions, sample_id, weight
        )) %>% rename(
            `TOC (mg/l)` = TOC_mg_l,
            `Org. Charge Density (meq/g of C)` = org_charge_density_meq_g_C,
            `EC (mS/M)` = EC_mS_m,
            `Absorbance 420mm` = Abs_F420_5cm, 
            `ADOM/DOC` = adom_doc,
            `Ionic strength` = Ionic.strength, 
            `Field pH` = pH_
        ) 


summary_stats <- data_table %>% group_by(mvm_id) %>% summarise(across(where(is.numeric), median, na.rm = TRUE),
            across(where(is.character), first))
min_values <- sapply(summary_stats, min, na.rm = TRUE)
max_values <- sapply(summary_stats, max, na.rm = TRUE)



table_summary <- sumtable(data_table %>% select(-mvm_id), out = "return", group.weights = data_with_weights$weight,summ=c('notNA(x)',
                'reldist::wtd.quantile (x, q=0.50, na.rm = TRUE, weight = wts)',
                'reldist::wtd.quantile (x, q=0.75, na.rm = TRUE, weight = wts) - reldist::wtd.quantile (x, q=0.25, na.rm = TRUE, weight = wts)'), summ.names = c("N", "Median", "IQR")) # %>% kable_styling(font_size = 10)

table_summary %>% 
  mutate(MinValue = round(as.numeric(min_values[Variable]), digits = 3),
         MaxValue = round(as.numeric(max_values[Variable]), digits = 3)) 

```

## Köhler


```{r load data}

# SAMPLE DATAFRAME 

df <- tibble(
    pH = seq(3.5, 7.5, by = 0.5),
    ANC = rep(0.197, 9),
    TOC = rep(10, 9),
    pCO2 = (1.079 * rep(10, 9) + 2.332) * 10^-4
)
```

```{r set parameters}
# pK
pKh <- 1.45
pK1 <- 6.35
pK2 <- 10.33
pKw <- 14

# pCO2
pCO2_list <- c(0.000316, 0.000632, 0.000949, 0.001265)
names(pCO2_list) <- c('1 atm', '2 atm', '3 atm', '4 atm' )

# TOC
a = 0.002062
b = 13.9

# Organic acid
SD <- 7
pKa1 <- 3.8
pKa2 <- 4.7
pKa3 <- 5.5
beta5.6 <- 6.3

# SD <- 7
# pKa1 <- 3.8
# pKa2 <- 4.7
# pKa3 <- 5.5
# beta5.6 <- 6.3
```

```{r calculate}
Kh <- 10^-pKh
K1 <- 10^-pK1
K2 <- 10^-pK2
Ka1 <- 10^-pKa1
Ka2<- 10^-pKa2
Ka3<- 10^-pKa3

```
```{r}
  h <- 10 ^ -pH
  oh <- (10 ^ -pKw) / h                                        # mol/l
  hco3 <- K1 * Kh * pCO2 / h                                  # mol/l
  co3 <- hco3 * K2 / h                         # mol/l
  Atot <- 10**-6 * (DOC * SD / 3)             # mol/l
  H3A <- Atot / (1 + (Ka1 / h) + (Ka1 * Ka2 / h ^ 2) + (Ka1 * Ka2 * Ka3 / h ** 3))
  H2A <- Ka1 * H3A / h
  HA <- Ka2 * H2A / h
  A <- Ka3 * HA / h
  ANCpH <-  10**3 * (oh + hco3 + 2 * co3 + H2A + 2 * HA + 3 * A - h) # mol/l
  rcoout <-  H2A + 2 * HA + 3 * A
```
